server:
  port: 8999
  servlet:
    context-path: /stability
spring:
  datasource:
    url: jdbc:mysql://47.108.29.69:40155/smartdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: stability
#  elasticsearch:
#    rest:
#      uris: 47.108.133.131
#    jest:
#      username: elastic
#      password: elastic

mybatis:
  type-aliases-package: com.bz
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml